# Dependencies
markdown:       kramdown
highlighter: 	rouge
gems: 		[jekyll-sitemap, jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'SKUU'
tagline:          'Sindikat kulturnih in umetniških ustvarjalcev'
description:      'Sindikat SKUU'
url:              https://skuuSindikat.github.io/

author:
  name:           'skuuSindikat'
  url:            https://skuuSindikat.github.io/

paginate:         3
