# Dependencies
markdown:       kramdown
highlighter: 	rouge
gems: 		[jekyll-sitemap, jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            'SKUU'
tagline:          ''
description:      'Sindikat SKUU'
url:              https://skuusindikat.github.io/

author:
  name:           'author'
  url:            https://skuusindikat.github.io/

paginate:         7


prose:
  rooturl: '_posts'
  siteurl: 'https://skuusindikat.github.io/'
  media: 'media'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "date"
        field:
          element: "hidden"
          value: "CURRENT_DATETIME"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "published"
        field:
          element: "hidden"
          value: "true"

